<!DOCTYPE html>
<html data-wf-page="5ea837e8c81001b668dffd4a" data-wf-site="5ea837e8c8100167b2dffd49">
<head>
  <meta charset="utf-8">
  <title><?= $profile->nameFirst . ' ' . $profile->nameLast . ' - ' . $profile->Company->name;?></title>
  <meta content="width=device-width, initial-scale=1" name="viewport">
<!--
    <link href="images/favicon.png" rel="shortcut icon" type="image/x-icon">
    <link href="images/webclip.jpg" rel="apple-touch-icon">
-->
    <style type="text/css">
    :root{
<?php foreach ($profile->css_variables as $css):?>
        --<?= $css->css_var;?>: <?= $css->css_value;?>;
<?php endforeach;?>
    }
    .container{

    }
    .container div{
        border:1px var(--color-accent) solid;
        padding:1em;
    }
    .box1{}
    .box2{}
    </style>
</head>
<body class="body">
    <!-- CONTAINER -->
    <div class="container">

        <!-- BOX1 -->
        <div class="box1">
            <?php if(!$profile->YTEmbed == ''):?>
            <div class="embeded_video"><?= $profile->YTEmbed;?></div>
            <?php endif;?>
        </div><!-- BOX1 -->

        <!-- BOX2 -->
        <div class="BOX2">

            <!-- IDENTITY -->
            <div class="identity">
                <div class="name"><?= trim($profile->nameFirst . ' ' . $profile->nameLast);?></div>
                <div class="jobTitle"><?= $profile->jobTitle;?></br>@ <?= $profile->Company->name;?></div>
            </div><!-- IDENTITY -->

            <!-- LINKS -->
            <div class="links">
            <?php foreach ($profile->links as $link):?>
                <div class="link">
                    <span class="link-label"><?= $link->label;?>: </span>
                    <a href="<?= $link->url;?>" target="_blank"><?= $link->label;?></a>
                </div>
            <?php endforeach;?>
            </div><!-- LINKS -->

            <!-- CREDIT -->
            <div class="credit">
                ©2021 BeProWise.com - <a href="https://beprowise.com" target="_blank" class="credit-links">BeProWise</a> by <a href="https://tekman.cc" target="_blank" class="credit-links">Tekman</a>
            </div><!-- CREDIT -->

        </div><!-- BOX2 -->
    </div><!-- CONTAINER -->
<!--
  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=5ea837e8c8100167b2dffd49" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="split/js/webflow.js" type="text/javascript"></script>
-->
  <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->
</body>
</html>